### PR TITLE
fix(ANT): add types for components

### LINKED ISSUE #626: [ANT] Typescript types
Introduce typescript types

### PR DESCRIPTION
**Pull request by rvsia**
closes #626 

- [x] check types
- [x] add script

### CODE REVIEW

File: packages/ant-component-mapper/src/files/plain-text.d.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import { ReactNode } from "react";
+
+import { TypographyProps } from 'antd/es/typography/Typography';
+import { ParagraphProps } from 'antd/es/typography/Paragraph';
+
+export interface PlainTextProps extends ParagraphProps {
+  label: ReactNode;
```
Comment (Hyperkid123) [inline packages/ant-component-mapper/src/files/plain-text.d.ts:7]: Is the plain text set up to consume nodes?

File: packages/ant-component-mapper/src/files/plain-text.js [hunk 2]
```diff
@@ -4,8 +4,8 @@ import PropTypes from 'prop-types';
 
 const { Paragraph } = Typography;
 
-const PlainText = ({ label, name, ...rest }) => (
-  <Typography>
+const PlainText = ({ label, name, TypographyProps, ...rest }) => (
+  <Typography {...TypographyProps}>
     {label.split('\n').map((paragraph, index) => (
```
Comment (Hyperkid123) [inline packages/ant-component-mapper/src/files/plain-text.js:9]: ^^ PlainText will crash if it has a Node type. Either modify this component it change the TS type ti string.

File: packages/ant-component-mapper/src/files/sub-form.d.ts [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  description?: ReactNode;
+  TitleRowProps?: RowProps;
+  TitleColProps?: ColProps;
+  TitleProps?: TitleProps;
+  DescriptionColProps?: ColProps;
+  DescriptionProps?: ParagraphProps;
+  DescriptionRowProps?: RowProps;
+  RowProps?: RowProps;
+  ColProps?: ColProps;
+  component: string;
```
Comment (Hyperkid123) [inline packages/ant-component-mapper/src/files/sub-form.d.ts:21]: I think this should not be here or be an optional type
