### PR TITLE
Fix docs datepickers imports

### LINKED ISSUE #1314: Documentation schema/is page is not being renderer
**Scope**: demo

**Description**

[schema/is page](https://data-driven-forms.org/schema/is) is not being rendered. (macOS/ ms edge)

Snímek obrazovky 2022-08-24 v 9 19 13

### PR DESCRIPTION
**Pull request by Hyperkid123**
fixes #1314

### CODE REVIEW

File: packages/react-renderer-demo/src/examples/components/conditions/is.js [hunk 1]
```diff
@@ -29,10 +29,13 @@ const componentMapper = {
   [componentTypes.TEXT_FIELD]: TextField,
 };
 
-const IsCondition = () => (
-  <div>
-    <FormRenderer FormTemplate={FormTemplate} componentMapper={componentMapper} schema={schema} onSubmit={console.log} />
-  </div>
-);
+const IsCondition = () => {
+  console.log(FormTemplate, componentMapper, FormRenderer);
```
Comment (rvsia) [inline packages/react-renderer-demo/src/examples/components/conditions/is.js:33]: console.log here

**Review by rvsia — APPROVED** [review]
