### PR TITLE
fix(pf3): allow select null value

### LINKED ISSUE #615: Option with empty value never gets selected in the DDF select
**Scope**: DDFv1 PF3

**Description**
> In select fields, when there's a nulll/0/empty value for an option, it never gets preselected if the field matches the value and the placeholder is shown. If you try to select it manually, the same thing happens, the default empty value tied to the placeholder takes preference.

https://github.com/ManageIQ/manageiq-ui-classic/issues/7174

### PR DESCRIPTION
**Pull request by Hyperkid123**
closes #615

If null option was selected, the label was not showing as selected value (although the null value was submitted). Snapshots are updated due to the dependency version update.

falsey-select

@skateman the other values (0, -1, ...) were working without any modification.

### CODE REVIEW

File: packages/pf3-component-mapper/demo/index.js [hunk 1]
```diff
@@ -121,7 +138,7 @@ const App = () => {
           onSubmit={console.log}
           componentMapper={componentMapper}
           FormTemplate={(props) => <FormTemplate {...props} />}
-          schema={schema}
+          schema={{fields: [selectSchema.fields[0]]}}
```
Comment (rvsia) [inline packages/pf3-component-mapper/demo/index.js:141]: I would keep demo unchanged to allow using buttons.

File: packages/pf3-component-mapper/src/files/select.js [hunk 2]
```diff
@@ -36,9 +36,14 @@ Select.propTypes = {
   description: PropTypes.node,
   placeholder: PropTypes.string,
   isDisabled: PropTypes.bool,
-  inputAddon: PropTypes.shape({ fields: PropTypes.array })
+  inputAddon: PropTypes.shape({ fields: PropTypes.array }),
+  allowNull: PropTypes.bool,
```
Comment (rvsia) [inline packages/pf3-component-mapper/src/files/select.js:40]: does this do something?

Comment (Hyperkid123) [reply packages/pf3-component-mapper/src/files/select.js:40]: Yes. The final form field treats null as falsey value and its converted to `undefined` by default.

**Review by rvsia — APPROVED** [review]

**Review by skateman — APPROVED** [review]
The Seal of Approval
