### PR TITLE
[MANAGER] Fix(renderer): use types from manager

### LINKED ISSUE #935: [v3] Remove final form dependency and fix types
**Scope**: renderer

**Description**

Remove all mentions of react-final-form from renderer

### PR DESCRIPTION
**Pull request by rvsia**
Fixes #935

**Description**

Changes to the usage of manager types, not DDF's.

### CODE REVIEW

File: packages/form-state-manager/src/form-state-manager/form-state-manager.tsx [hunk 1]
```diff
@@ -12,7 +12,7 @@ import { Debug } from '../manager-api';
 
 export interface FormStateManagerProps {
   onSubmit: (values: AnyObject) => void;
-  children?: (props: AnyObject) => React.ReactNode;
+  children?: (props: AnyObject) => React.ReactNode | React.ReactNode;
```
Comment (Hyperkid123) [inline packages/form-state-manager/src/form-state-manager/form-state-manager.tsx:15]: DO we need the same type twice?

**Review by Hyperkid123 — APPROVED** [review]
