### PR TITLE
fix(ant,pf4): copy css to build folders

### LINKED ISSUE #931: [V3] Refactor S/CSS to CSS-in-JS for version 3
**Scope**: All

**Description**

- [x] ant (css/scss) @rvsia https://github.com/data-driven-forms/react-forms/pull/937
- [x] blueprint @rvsia https://github.com/data-driven-forms/react-forms/pull/939
- [x] carbon @rvsia https://github.com/data-driven-forms/react-forms/pull/940
- [x] pf4 @rvsia https://github.com/data-driven-forms/react-forms/pull/942
- [x] geneate CSS in package files (PF4, ant) @rvsia https://github.com/data-driven-forms/react-forms/pull/968

### PR DESCRIPTION
**Pull request by rvsia**
Fixes #931 

**Description**

CSS files are copied to their build folders.

### CODE REVIEW

File: scripts/copy-css.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+      copyFileSync(file, `./${fileName}`);
+      copyFileSync(file, `./esm/${fileName}`);
+    });
+  });
+}
+
+async function run() {
+  try {
+    await copyCss();
```
Comment (Hyperkid123) [inline scripts/copy-css.js:25]: There is no need ofr using async flags when you are using `sync` versions of the FS functions

**Review by Hyperkid123 — APPROVED** [review]
