### PR TITLE
fix(carbon): do not use absolute import paths

### LINKED ISSUE #1298: Upgrading to carbon-components-react 7.56 causing components to break
After upgrading to carbon-components-react 7.56 I ran into this bug with the Carbon DDF dual list select component.
```

Uncaught (in promise) Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of DualListSelectInner
```

Not sure if this affects other components but this is the only one I found.

### PR DESCRIPTION
**Pull request by Hyperkid123**
There are import path changes in minor releases. Using absolute imports
will cause backwads compatibility issues.

Fixes #1298

### CODE REVIEW

**Review by rvsia — APPROVED** [review]

File: packages/mui-component-mapper/src/date-picker/date-picker.d.ts [hunk 1]
```diff
@@ -6,6 +6,10 @@ type InternalDatePickerProps<TInputDate, TDate> = MuiDatePickerProps<TInputDate,
 }
 
 export type DatePickerProps<TInputDate, TDate> = InternalDatePickerProps<TInputDate, TDate> & UseFieldApiComponentConfig;
+<<<<<<< Updated upstream
```
Comment (GilbertCherrie) [inline packages/mui-component-mapper/src/date-picker/date-picker.d.ts:9]: @Hyperkid123 Should these be removed? I think these are the git comments but might cause parsing errors.

Comment (Hyperkid123) [reply packages/mui-component-mapper/src/date-picker/date-picker.d.ts:9]: Oh yeah. Nice catch!
