### PR TITLE
fix(pf4): migrate to css for select styles.

### LINKED ISSUE #59: Use css for select component instead of css in js
Use PF4 css variables and some prefix for class names

### PR DESCRIPTION
**Pull request by Hyperkid123**
closes #59 

- use scss instead of css in JS for pf4 select component.

### CODE REVIEW

File: packages/pf4-component-mapper/src/form-fields/select/multi-value-remove.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+
```
Comment (rvsia) [inline packages/pf4-component-mapper/src/form-fields/select/multi-value-remove.js]: blank line

File: packages/pf4-component-mapper/src/form-fields/select/multi-value-remove.js [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+import { TimesCircleIcon } from '@patternfly/react-icons';
+
+const MultiValueRemove = props => (
+  <components.MultiValueRemove { ...props }>
+    <TimesCircleIcon />
+  </components.MultiValueRemove>
+);
+
+export default MultiValueRemove;
+
```
Comment (rvsia) [inline packages/pf4-component-mapper/src/form-fields/select/multi-value-remove.js]: blank line II.

File: packages/pf4-component-mapper/src/form-fields/select/value-container.js [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+ValueContainer.defaultProps = {
+  isMulti: false,
+  selectProps: {
+    showLessLabel: 'Show less',
+    showMoreLabel: 'more',
+  },
+};
+
+export default ValueContainer;
+
```
Comment (rvsia) [inline packages/pf4-component-mapper/src/form-fields/select/value-container.js]: blank line
