### PR TITLE
fix(ant): refactor and add customization for each component

### LINKED ISSUE #630: [ANT] Check if all components are customizable

### PR DESCRIPTION
**Pull request by rvsia**
closes #630

### CODE REVIEW

File: packages/ant-component-mapper/src/files/form-template.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ import FormTemplate from '@data-driven-forms/common/src/form-template';
 const { Title, Paragraph } = Typography;
 
 const Form = ({ layout, children, onSubmit, ...props }) => (
-  <AntForm onFinish={onSubmit} layout={layout ? layout : 'vertical'}>
+  <AntForm onFinish={onSubmit} layout={layout ? layout : 'vertical'} {...props}>
```
Comment (Hyperkid123) [inline packages/ant-component-mapper/src/files/form-template.js:9]: can we make the `layout` either a default prop or assign it in the function arguments?
