### PR TITLE
fix(mui): add default field array

### LINKED ISSUE #421: No Field Array mapping for material ui
**Scope**:
MUI mapper

**Description**
The field array type is not available in the mui mapper and throws an error. Tried using the mapping from patternFly and works well.

**Schema**
For example:
```
{
    fields: [
        {
            component: componentTypes.TEXT_FIELD,
            name: "name",
            label: "Your name"
        },
        {
            component: componentTypes.FIELD_ARRAY,
            fieldKey: "contacts",
            name: "contacts",
            label: "Contacts",
            itemDefault: { type: '', value: '' },
            fields: [
                {
                    component: componentTypes.TEXT_FIELD,
                    name: "type",
                    label: "Type"
                },
                {
                    component: componentTypes.TEXT_FIELD,
                    name: "value",
                    label: "Value"
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by rvsia**
Same as PF4

image

I have remove the `hr` from mockups, because it actually looks as an another MUI field. :smiley: 

+ Allows to revert `remove` actions

materialuifieldarray

TODO:
- [x] docs
- [x] tests

closes #421

### CODE REVIEW

File: packages/mui-component-mapper/src/files/field-array.js [hunk 1]
```diff
@@ -0,0 +1,248 @@
+import React, { useReducer } from 'react';
+import PropTypes from 'prop-types';
+import { useFormApi, FieldArray } from '@data-driven-forms/react-form-renderer';
+
+import Grid from '@material-ui/core/Grid';
```
Comment (Hyperkid123) [inline packages/mui-component-mapper/src/files/field-array.js:5]: So here, we actually want to use shorthand imports `import {Grid, Button, ...} from 'material-ui/core'`. The babel plugin is taking care of importing correct components for the cjs/esm builds.

File: packages/mui-component-mapper/src/files/field-array.js [hunk 2]
```diff
@@ -0,0 +1,248 @@
...
+import Button from '@material-ui/core/Button';
+import Typography from '@material-ui/core/Typography';
+import FormControl from '@material-ui/core/FormControl';
+import FormHelperText from '@material-ui/core/FormHelperText';
+import { makeStyles } from '@material-ui/core/styles';
```
Comment (Hyperkid123) [inline packages/mui-component-mapper/src/files/field-array.js:10]: ^^ does not apply on `core/styles` imports.

File: packages/mui-component-mapper/src/files/field-array.js [hunk 3]
```diff
@@ -0,0 +1,248 @@
...
+            };
+
+            const removeWrapper = (index) => {
+              dispatch({ type: 'action', action: { action: 'remove', value: value[index] } });
+              remove(index);
+            };
+
+            const undo = () => {
+              push(state.history[state.index - 1].value);
+
```
Comment (Hyperkid123) [inline packages/mui-component-mapper/src/files/field-array.js:160]: extra lines

File: packages/mui-component-mapper/src/files/field-array.js [hunk 4]
```diff
@@ -0,0 +1,248 @@
...
+                )}
+                <Grid item xs={12}>
+                  {value.length <= 0 ? (
+                    <Typography variant="body1" gutterBottom className={classes.centerText}>
+                      {noItemsMessage}
+                    </Typography>
+                  ) : (
+                    map((name, index) => (
+                      <ArrayItem
+                        key={`${name}-${index}`}
```
Comment (Hyperkid123) [inline packages/mui-component-mapper/src/files/field-array.js:201]: I dont think that we need the `-${index}` suffix. The name from the map function should be always unique.

File: packages/react-renderer-demo/src/app/src/doc-components/mui-field-array.md [hunk 5]
```diff
@@ -0,0 +1,49 @@
+MUI component mapper provides an experimental implementation of PF4 field arrays.
```
Comment (Hyperkid123) [inline packages/react-renderer-demo/src/app/src/doc-components/mui-field-array.md:1]: I think the PF4 reference does not belong here.

File: packages/react-renderer-demo/src/app/src/doc-components/pf4-field-array.md [hunk 6]
```diff
@@ -0,0 +1,44 @@
+PF4 component mapper provides an experimental implementation of PF4 field arrays.
```
Comment (Hyperkid123) [inline packages/react-renderer-demo/src/app/src/doc-components/pf4-field-array.md:1]: Same here there are two references to PF4

**Comment by rvsia** [comment]
All notes has been fixed.
